# dic={"j":23,"a":1,"n":14}
# print(dic.items())
# print(len(dic))
# slicing="abcdefghijklmno"
# print(slicing[0:2])
"""trying splitt method"""
# a=input("enter a numbrer")
# as_list=a.split()
# as_list_2=[]
# for x in as_list:
#     as_list_2.append(int(x))
# as_list_3=[]
# for y in as_list_2:
#     if y not in as_list_3:
#         as_list_3.append(y)
# as_list_3.sort(reverse=True)

# print(as_list_3)
# list=[1,2,3,4,5,6,7,8,9]
# h=min(list)
# print(h)
take=list((input("enter a number : ")))
inte=int(take)
print(inte)